name: Run Tests

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main

jobs:
  Python-Unit-Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add poetry to our path
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Run poetry install
        run: poetry install

      - name: Run tests
        run: poetry run pytest
